spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: root
    password: 56824
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  properties:
    hibernate:
      types:
        print:
          banner: false