spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: root
    password: 56824
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        types:
          print:
            banner: false
    show-sql: true
    open-in-view: false
